########################
#                      #
#   COSMIN by Sachin   # 
#                      #
########################

# Thank you for downloading cosmin 
# For feature requests or bug reports contact me on discord https://discord.gg/VdfqQZjHrJ or pm me directly at sachin#8481


# Messages
messages:
  no-permission: "&7[Cosmin] &eYou dont have permission to run the command"
  cant-deequip: "&7[Cosmin] &eThe armor is forced equiped cant remove it"
  less-balance: "&7[Cosmin] &eYou dont have enough balance for purchase"

# Aliases for command used to open cosmin GUI
# restart/reload may require for this option to apply changes
aliases: [cosmetics,cos]

# inventory titles for various gui
# supports placeholder-api
# new placeholder %page% to determine which page player is on
inventory-titles:
  main-gui: "Cosmetic Gui"
  helmet-page: "Helmet: %page%"
  chestplate-page: "Chestplate: %page%"
  leggings-page: "Leggings: %page%"
  boots-page: "Boots: %page%"
  offhand-page: "OffHand: %page%"
  cosmetic-sets-page: "Cosmetic Sets: %page%"
  confirm-page: "Are you sure?"
  store-page: "Store: %page%"

# MySQL database used to sync every player's cosmin inventory.
# ATTENTION: this will not sync wardrobe item pieces you create in items folder.
# While using database its recommended to turn all slottypes to false in allow-external-armor 
# to prevent players from transporting items from one server to another.
database:
  enabled: false
  host: address
  port: port
  username: ""
  password: ""
  name: "name of data base"
  table-name: cosmin_player_data

# weather or not players are allowed to place there own armor items in fake armor slots
# set all to false if using MySQL database
allow-external-armor:
  HEAD: true
  CHEST: true
  LEGS: true
  FEET: true
  OFFHAND: true

# weather or not wardrobe is enabled for the specified slot
wardrobe-enabled:
  HEAD: true
  CHEST: true
  LEGS: true
  FEET: true
  OFFHAND: true 

# inventory short cuts used to do certain actions ONLY in cosmetic GUI
# toggle-display = on clicked it will toggle the display of armor present in respective fake equipment slot
# open-wardrobe = on clicked it will open the wardrobe inventory page for respective fake equipment slot
# clear-wardrobe-item = on clicked it will remove the item in respective slot only if its wardrobe item
# open-cosmetic-set-gui = on clicked(item present in slot 0) it will open cosmetic set gui
# clear-cosmetic-set = on clicked it will clear the entire fake armor set player is wearing 
hot-keys:
  toggle-display: LEFT
  open-wardrobe: RIGHT
  clear-wardrobe-item: DROP
  open-cosmetic-set-gui: RIGHT
  clear-cosmetic-set: DROP

# weather or not to enable cosmetic sets
# this can be toggled per player too with cosmin.cosmeticset permission, players without this permission will not able to see the cosmetic sets button
enable-cosmetic-set: true

# weather or not to enable stores where player can buy items/sets 
# requires economy plugin like essentials/cmi and vault
enable-store: true

# this is used to display item/set cost present in store
shop-item-lore:
  - "&a------------"
  - "&6Cost: &e%cost% $"
  - "&a------------"

# the string that will be added to display name of toggle items(enable and disable) to determin what armor type the slot is
# example: "Enabled [HELMET]"
toggle-item-tooltip:
  HEAD: "&7[HELMET]"
  CHEST: "&7[CHEST]"
  LEGS: "&7[LEGS]"
  FEET: "&7[FEET]"
  OFFHAND: "&7[OFFHAND]"

# list of materials that will not be displayed when equiped
blacklist-materials:
  - TRIDENT
  
