########################
#                      #
#   COSMIN by Sachin   # 
#                      #
########################

# Thank you for downloading cosmin 
# For feature requests or bug reports contact me on discord https://discord.gg/VdfqQZjHrJ or pm me directly at sachin#8481



# Aliases for command used to open cosmin GUI
# restart/reload may require for this option to apply changes
aliases: [cosmetics,cos]

# inventory titles for various gui
# supports placeholder-api
# new placeholder %page% to determine which page player is on
inventory-titles:
  main-gui: "Cosmetic Gui"
  helmet-page: "Helmet: %page%"
  chestplate-page: "Chestplate: %page%"
  leggings-page: "Leggings: %page%"
  boots-page: "Boots: %page%"
  offhand-page: "OffHand: %page%"
  cosmetic-sets-page: "Cosmetic Sets: %page%"
  confirm-page: "Are you sure?"
  store-page: "Store: %page%"

# MySQL database used to sync every player's cosmin inventory.
# ATTENTION: this will not sync wardrobe item pieces you create in items folder.
# While using database its recommended to turn all slottypes to false in allow-external-armor 
# to prevent players from transporting items from one server to another.
database:
  enabled: false
  # Possible database types: mysql,mariadb
  type: mysql
  host: address
  port: port
  username: ""
  password: ""
  name: "name of data base"
  table-name: cosmin_player_data
  # in seconds
  max-life-time: 1800
  auto-reconnect: true


# inventory short cuts used to do certain actions ONLY in cosmetic GUI
# toggle-display = on clicked it will toggle the display of armor present in respective fake equipment slot
# open-wardrobe = on clicked it will open the wardrobe inventory page for respective fake equipment slot
# clear-wardrobe-item = on clicked it will remove the item in respective slot only if its wardrobe item
# open-cosmetic-set-gui = on clicked(item present in slot 0) it will open cosmetic set gui
# clear-cosmetic-set = on clicked it will clear the entire fake armor set player is wearing 
hot-keys:
  toggle-display: LEFT
  open-wardrobe: RIGHT
  clear-wardrobe-item: DROP
  open-cosmetic-set-gui: RIGHT
  clear-cosmetic-set: DROP

# weather or not to enable cosmetic sets
# this can be toggled per player too with cosmin.cosmeticset permission, players without this permission will not able to see the cosmetic sets button
enable-cosmetic-set: false

# weather or not to enable stores where player can buy items/sets 
# requires economy plugin like essentials/cmi and vault
enable-store: false

# this is used to display item/set cost present in store
shop-item-lore:
  - "%lore%"
  - "&a------------"
  - "&6Cost: &e%cost% $"
  - "&a------------"

# the string that will be added to display name of toggle items(enable and disable) to determin what armor type the slot is
# example: "Enabled [HELMET]"
toggle-item-tooltip:
  HEAD: "&7[HELMET]"
  CHEST: "&7[CHEST]"
  LEGS: "&7[LEGS]"
  FEET: "&7[FEET]"
  OFFHAND: "&7[OFFHAND]"

# weather or not players are allowed to place there own armor items in fake armor slots
# set all to false if using MySQL database
allow-external-armor:
  HEAD: true
  CHEST: true
  LEGS: true
  FEET: true
  OFFHAND: true

# weather or not players are allowed to hide there orignal armor by keeping the respective fake slot empty
# this can changed for invdividual players too with cosmin.hidearmor[slotname] or use cosmin.hidearmor.* to take all slots into account
allow-empty-slots:
  HEAD: true
  CHEST: true
  LEGS: true
  FEET: true
  OFFHAND: true

# weather or not wardrobe is enabled for the specified slot
wardrobe-enabled:
  HEAD: false
  CHEST: false
  LEGS: false
  FEET: false
  OFFHAND: false 

# if set to true: when player closes wardrobe it will open the cosmetic gui 
open-cosmetic-gui-on-wardrobe-close: true  

# list of materials that cant be placed in fake armor slots
# Pro tip: 
  # use NAME$ to take those names into account which end with "NAME" eg. "BANNER$"
  # use ^NAME to take those names into acccount which start with "NAME" eg. "^NETHERITE"
blacklist-materials:
  HEAD: []
  CHEST: []
  LEGS: []
  FEET: []
  OFFHAND: [TRIDENT]

# weather or not player should drop there items present in cosmin gui on death
# Bypass permission: cosmin.deathdrops.bypass
drop-items-on-death: true

#  the amount of delay in ticks, to show the changes to armor after closing player inventory or cosmetic inventory
delay-after-equip: 2

# customize the main gui
# any other cosmin item id or Material id can be used instead of "filler-glass"
main-gui-layout:
  - set-button|filler-glass|toggle-head-slot|toggle-chest-slot|toggle-legs-slot|toggle-feet-slot|toggle-offhand-slot|filler-glass|filler-glass
  - filler-glass|filler-glass|head-slot|chest-slot|legs-slot|feet-slot|offhand-slot|filler-glass|filler-glass


